### DB INFORMATIONS
POST http://localhost:3000/db-client-connect/create
Content-Type: application/json

{
  "host": "127.0.0.1",
  "password": "root_password",
  "port": 3306,
  "type": "mysql",
  "username": "isaiasiotti",
  "db_name": "dbcliente"
}

### CONNECT
POST http://localhost:3000/db-client-connect/connect
Content-Type: application/json